name: Lint code

on:
  push:
  pull_request:
    branches-ignore: [ main ]

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Run pre-commit
      uses: pre-commit/action@v3.0.0
